
services:
  odoo:
    image: odoo:17
    ports:
      - "8069:8069"
    volumes:
      - ./server:/mnt/odoo
      - ./server/addons:/mnt/odoo/addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    command: ["odoo", "-c", "/etc/odoo/odoo.conf"]

volumes:
  odoo-db-data:
